name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
          - os: macos-13
            arch: x86_64
          - os: macos-latest
            arch: aarch64

    runs-on: ${{ matrix.settings.os }}

    steps:
      # Check out the repository.
      - uses: actions/checkout@v4
      - name: Print OS ${{ matrix.settings.os }}
        run: uname -a
      - name: Print Architecture ${{ matrix.settings.arch }}
        run: uname -m

      # Install Bun.
      - name: Install Bun on ${{ matrix.settings.os }} and ${{ matrix.settings.arch }}
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
          # Append Bun's bin folder to the GitHub Actions PATH.
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
          bun --version

      # (Optional) Install dependencies if you use bun install.
      - name: Install Dependencies
        run: bun install

      - name: Lint Code
        run: bun lint

      - name: Unit Tests
        run: bun test:unit

      - name: Benchmark
        run: bun benchmark
        env:
          # To write to PRs and commits
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}